name: CloudPermissions
main: eu.cloudnetservice.cloudpermission.PermissionPlugin
version: ${permission.version}

api-version: 1.13
author: CloudNetService

depend: [CloudNetAPI]

description: CloudNet Permission System
website: https://cloudnetservice.eu/